// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LoopCreateParams = { threadId: string, name?: string | null, prompt: string, everySeconds: bigint, };
